#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "glances"
name = "Glances"
description.en = "Real-time monitoring tool"
description.fr = "Outil de suivi en temps réel"

version = "4.3.0.8 ~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "free"
website = "https://nicolargo.github.io/glances/?ref=selfh.st"
demo = "https://demo.example.com"
admindoc = "https://glances.readthedocs.io/en/latest/index.html"
code = "https://github.com/nicolargo/glances"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/example"

    [install.init_main_permission]
    type = "group"
    default = "visitors"


    [install.admin]
    type = "user"

    [install.password]
    # this is a generic question - ask strings are automatically handled by YunoHost's core
    # Note that user-provided passwords questions are not automatically saved as setting
    help.en = "Use the help field to add an information for the admin about this question."
    help.fr = "Utilisez le champ aide pour ajouter une information à l'intention de l'administrateur à propos de cette question."
    type = "password"

[resources]

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "python3-dev, python3-venv, python3, python3-pip, libcurl4-openssl-dev, libssl-dev"
